### ISSUE TITLE
Bug on SVM (classification) -> plot_svc_function

### ISSUE THREAD

**Issue by SanyHe** [ZJUEarthData/geochemistrypy#46]
(1) System Environment:
+ System version: macOS Catalina version 10.15.7
+ Python version: 3.9.7  

(2) Problem:
When I wanna plot the decision boundary of SVC, the error occurs.

(3) Log:
```python
PLot_SVC_Function
Traceback (most recent call last):
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/main.py", line 233, in <module>
    main()
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/main.py", line 223, in main
    run.activate(X, y)
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../process/classify.py", line 34, in activate
    self.clf_workflow.special_components()
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../model/classification.py", line 176, in special_components
    self.plot_svc_function()
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../model/classification.py", line 169, in plot_svc_function
    P = clf.decision_function(xy).reshape(X.shape)
  File "/usr/local/lib/python3.9/site-packages/sklearn/svm/_base.py", line 583, in decision_function
    dec = self._decision_function(X)
  File "/usr/local/lib/python3.9/site-packages/sklearn/svm/_base.py", line 408, in _decision_function
    X = self._validate_for_predict(X)
  File "/usr/local/lib/python3.9/site-packages/sklearn/svm/_base.py", line 484, in _validate_for_predict
    raise ValueError("X.shape[1] = %d should be equal to %d, "
ValueError: X.shape[1] = 2 should be equal to 4, the number of features at training time
```

(4) Idea:
Maybe it is about the data dimensions.

**Comment by PotatoXi** [comment]
1) System Environment:

Systerm version: Windows 11 
Python version: 3.9.7

(2) Problem:
An error occurred during running.

(3) Log:
PLot_SVC_Function
Traceback (most recent call last):
  File "D:\code\geochemistrypy\geochemistrypy\client\main.py", line 233, in <module>
    main()
  File "D:\code\geochemistrypy\geochemistrypy\client\main.py", line 223, in main
    run.activate(X, y)
  File "D:\code\geochemistrypy\geochemistrypy\process\classify.py", line 34, in activate
    self.clf_workflow.special_components()
  File "D:\code\geochemistrypy\geochemistrypy\model\classification.py", line 177, in special_components
    self.plot_svc_function()
  File "D:\code\geochemistrypy\geochemistrypy\model\classification.py", line 169, in plot_svc_function
    P = clf.decision_function(xy).reshape(X.shape)
  File "D:\Anaconda\lib\site-packages\sklearn\svm\_base.py", line 756, in decision_function
    dec = self._decision_function(X)
  File "D:\Anaconda\lib\site-packages\sklearn\svm\_base.py", line 514, in _decision_function
    X = self._validate_for_predict(X)
  File "D:\Anaconda\lib\site-packages\sklearn\svm\_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "D:\Anaconda\lib\site-packages\sklearn\base.py", line 585, in _validate_data
    self._check_n_features(X, reset=reset)
  File "D:\Anaconda\lib\site-packages\sklearn\base.py", line 400, in _check_n_features
    raise ValueError(
ValueError: X has 2 features, but SVC is expecting 6 features as input.

4）ideas:
we can add a ‘if....else....’，about”Dichotomize the two selected elements and draw an image“,

**Comment by Jin-sjh** [comment]
I have used the method of dimension reduction to deal with the bug and thank you  for your great advice.
