### ISSUE TITLE
Bug on xgboost(classification) -> plot _feature_importance

### ISSUE THREAD

**Issue by SanyHe** [ZJUEarthData/geochemistrypy#51]
(1) System Environment:
+ System version: macOS Catalina version 10.15.7
+ Python version: 3.9.7  

(2) Problem:
When I wanna draw the feature importance graph of xgboost, the error occurs.

(3) Log:
```python
-----* Feature Importance *-----
Traceback (most recent call last):
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/main.py", line 233, in <module>
    main()
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/main.py", line 223, in main
    run.activate(X, y)
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../process/classify.py", line 36, in activate
    self.clf_workflow.special_components()
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../model/classification.py", line 557, in special_components
    self._feature_importance()
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../model/classification.py", line 527, in _feature_importance
    for feature_name, score in zip(list(columns_name), self.model.feature_importances_):
  File "/usr/local/lib/python3.9/site-packages/xgboost/sklearn.py", line 746, in feature_importances_
    score = b.get_score(importance_type=self.importance_type)
  File "/usr/local/lib/python3.9/site-packages/xgboost/core.py", line 1879, in get_score
    raise ValueError(msg.format(importance_type))
ValueError: importance_type mismatch, got 'None', expected one of ['weight', 'gain', 'cover', 'total_gain', 'total_cover']
```

(4) Idea:

**Comment by Brad-zqh** [comment]
def __init__(...............,  importance_type: Optional[str] = 'weight',.............)
